"""add_risk_config_table

Revision ID: 2e2c57bba3ae
Revises: 64a1c753f9ce
Create Date: 2026-04-01 23:25:51.658977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '2e2c57bba3ae'
down_revision: Union[str, None] = '64a1c753f9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_configs',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('score_mode', sa.String(length=20), nullable=False),
    sa.Column('tier_thresholds', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_configs')
    # ### end Alembic commands ###
