"""add_cluster_metadata_and_embedding_source

Revision ID: 64a1c753f9ce
Revises: a62a7e3e7ba5
Create Date: 2026-04-01 01:23:54.275817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64a1c753f9ce'
down_revision: Union[str, None] = 'a62a7e3e7ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_sessions', sa.Column('cluster_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('scan_sessions', sa.Column('embedding_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_sessions', 'embedding_source')
    op.drop_column('scan_sessions', 'cluster_metadata')
    # ### end Alembic commands ###
