"""add clinical_analyses table

Revision ID: 690429306a27
Revises: ae3039195dc7
Create Date: 2026-04-02 05:22:44.342490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '690429306a27'
down_revision: Union[str, None] = 'ae3039195dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_analyses',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('systemic_analysis', sa.Text(), nullable=True),
    sa.Column('root_systems', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cascade_chains', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('key_patterns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('actionable_insights', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_source', sa.String(length=20), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('context_token_count', sa.Integer(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_clinical_analyses_patient_id'), 'clinical_analyses', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_analyses_patient_id'), table_name='clinical_analyses')
    op.drop_table('clinical_analyses')
    # ### end Alembic commands ###
