"""initial_schema

Revision ID: a62a7e3e7ba5
Revises: 
Create Date: 2026-04-01 00:44:36.519181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a62a7e3e7ba5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('encrypted_first_name', sa.Text(), nullable=False),
    sa.Column('encrypted_last_name', sa.Text(), nullable=False),
    sa.Column('encrypted_middle_name', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('condition_trends',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('condition_icd10', sa.String(length=20), nullable=True),
    sa.Column('condition_name', sa.Text(), nullable=False),
    sa.Column('organ_system', sa.String(length=100), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=False),
    sa.Column('trend_slope', sa.Float(), nullable=False),
    sa.Column('sessions_analyzed', sa.Integer(), nullable=False),
    sa.Column('first_score', sa.Float(), nullable=False),
    sa.Column('last_score', sa.Float(), nullable=False),
    sa.Column('change_points', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_trends_patient_id'), 'condition_trends', ['patient_id'], unique=False)
    op.create_table('scan_sessions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('scan_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_report_url', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('report_section', sa.String(length=100), nullable=True),
    sa.Column('organ_system', sa.String(length=100), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('analysis_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_sessions_patient_id'), 'scan_sessions', ['patient_id'], unique=False)
    op.create_table('recovery_plans',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('organ_system_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_conditions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_interventions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('lifestyle_recommendations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('nutritional_recommendations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('monitoring_plan', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_recovery_plans_patient_id'), 'recovery_plans', ['patient_id'], unique=False)
    op.create_table('scan_entries',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('condition_name', sa.Text(), nullable=False),
    sa.Column('condition_icd10', sa.String(length=20), nullable=True),
    sa.Column('condition_snomed', sa.String(length=20), nullable=True),
    sa.Column('anatomical_location', sa.Text(), nullable=True),
    sa.Column('anatomical_fma_id', sa.String(length=20), nullable=True),
    sa.Column('organ_system', sa.String(length=100), nullable=True),
    sa.Column('report_section', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('green_ratio', sa.Float(), nullable=True),
    sa.Column('red_ratio', sa.Float(), nullable=True),
    sa.Column('marker', sa.String(length=10), nullable=True),
    sa.Column('embedding_vector', Vector(768), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_entries_session_id'), 'scan_entries', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_entries_session_id'), table_name='scan_entries')
    op.drop_table('scan_entries')
    op.drop_index(op.f('ix_recovery_plans_patient_id'), table_name='recovery_plans')
    op.drop_table('recovery_plans')
    op.drop_index(op.f('ix_scan_sessions_patient_id'), table_name='scan_sessions')
    op.drop_table('scan_sessions')
    op.drop_index(op.f('ix_condition_trends_patient_id'), table_name='condition_trends')
    op.drop_table('condition_trends')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
