"""add_report_generated_at_to_sessions

Revision ID: ae3039195dc7
Revises: 2e2c57bba3ae
Create Date: 2026-04-02 00:10:05.941041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'ae3039195dc7'
down_revision: Union[str, None] = '2e2c57bba3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_sessions', sa.Column('report_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_sessions', 'report_generated_at')
    # ### end Alembic commands ###
