"""Report parser — extracts structured data from Med Bed scan reports.

Supports PDF (primary), CSV, JSON, and image formats.

The Tesla Med Bed PDF format (generated by FastReport) has this structure:
  - Header: patient info (name, age, DOB, address, phone, blood group)
  - Section A) SIMULAR PROCESSES — pathology conditions
  - Section E) MICROORGANISMS AND HELMINTHS — microbial findings
  - Each section has numbered organ systems (01-12)
  - Each entry: CONDITION_NAME on one line, score (0.xxx) right-aligned, then
    optional ANATOMICAL_LOCATION on the next indented line
"""

import io
import json
import logging
import re
import subprocess
import tempfile
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)

# ---------- Organ system mapping ----------

ORGAN_SYSTEMS = {
    "01": "01 CORE PRODUCT",
    "02": "02 DIGESTIVE SYSTEM",
    "03": "03 RESPIRATORY SYSTEM",
    "04": "04 UROGENITAL SYSTEM",
    "05": "05 CARDIOVASCULAR SYSTEM",
    "06": "06 BLOOD AND LYMPH",
    "07": "07 ENDOCRINE SYSTEM",
    "08": "08 NERVOUS SYSTEM",
    "09": "09 OSTEOSKELETAL SYSTEM",
    "10": "10 SENSORY SYSTEM",
    "11": "11 ULTRA MICRO SCAN",
    "12": "12 DNA RNA",
}

# Regex patterns for the Med Bed PDF text format
RE_SECTION_HEADER = re.compile(
    r"^([A-E])\)\s+(.+)$", re.MULTILINE
)
RE_ORGAN_SYSTEM = re.compile(
    r"^\s*(\d{2})\s+([A-Z][A-Z &/-]+)$", re.MULTILINE
)
RE_SCORE = re.compile(r"\b(0\.\d{3})\b")
RE_PAGE_FOOTER = re.compile(
    r"^\s*\d+\s*/\s*\d+\s*$", re.MULTILINE
)
RE_TIMESTAMP = re.compile(
    r"\d{1,2}/\d{1,2}/\d{4}\s+\d{1,2}:\d{2}:\d{2}", re.MULTILINE
)
RE_NAV_TABS = re.compile(
    r"^\s*GI\s+Cardiovascular\s+Immune\s+Brain\s+Breath\s+Bones\s+"
    r"Endocrine\s+Vision\s+Hemolymph\s+Genitourinary\s*$",
    re.MULTILINE,
)
RE_MARKER = re.compile(r"\s*#\s*([A-Z])\s*$")
RE_PATIENT_FIELD = re.compile(
    r"(FIRST NAME|LAST NAME|MIDDLE NAME|AGE|BITHDAY|BIRTHDAY|ADDRESS|"
    r"BLOOD GROUP|PHONE)\s*:", re.IGNORECASE
)


async def parse_report(
    file_bytes: bytes, report_type: str, filename: str = ""
) -> dict:
    """Parse a report file and return structured data.

    Returns:
        dict with keys:
            - patient_info: dict of patient demographics
            - entries: list of entry dicts
    """
    if report_type == "pdf":
        return _parse_pdf(file_bytes)
    elif report_type == "csv":
        return _parse_csv(file_bytes)
    elif report_type == "json":
        return _parse_json(file_bytes)
    elif report_type == "image":
        return _parse_image(file_bytes)
    else:
        raise ValueError(f"Unsupported report type: {report_type}")


def _parse_pdf(file_bytes: bytes) -> dict:
    """Parse a Tesla Med Bed PDF report using pdftotext.

    Uses pdftotext (poppler) for structured text extraction. Falls back to
    OCR via pytesseract only if pdftotext yields no usable text.
    """
    text = _extract_text_pdftotext(file_bytes)

    if not text or len(text.strip()) < 50:
        logger.info("pdftotext yielded minimal text, falling back to OCR")
        text = _extract_text_ocr(file_bytes)

    if not text:
        raise ValueError("Could not extract any text from PDF")

    return _parse_medbed_text(text)


def _extract_text_pdftotext(file_bytes: bytes) -> str:
    """Extract text from PDF using poppler's pdftotext."""
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp.write(file_bytes)
        tmp_path = tmp.name

    try:
        result = subprocess.run(
            ["pdftotext", "-layout", tmp_path, "-"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        return result.stdout
    except FileNotFoundError:
        logger.warning("pdftotext not found, install poppler-utils")
        return ""
    except subprocess.TimeoutExpired:
        logger.warning("pdftotext timed out")
        return ""
    finally:
        Path(tmp_path).unlink(missing_ok=True)


def _extract_text_ocr(file_bytes: bytes) -> str:
    """Fallback: extract text from PDF using OCR (pytesseract + pdf2image)."""
    try:
        from pdf2image import convert_from_bytes
        import pytesseract

        images = convert_from_bytes(file_bytes, dpi=300)
        text_parts = []
        for img in images:
            text_parts.append(pytesseract.image_to_string(img))
        return "\n".join(text_parts)
    except Exception as e:
        logger.error("OCR extraction failed: %s", e)
        return ""


def _extract_report_timestamp(text: str) -> str | None:
    """Extract the report generation timestamp from the PDF text.

    The Med Bed report has a generation timestamp in the footer of each page,
    e.g., "3/30/2026 3:46:05". We extract the first occurrence.
    """
    match = RE_TIMESTAMP.search(text)
    if match:
        raw = match.group(0).strip()
        logger.info("Extracted report generation timestamp: %s", raw)
        return raw
    return None


def _parse_medbed_text(text: str) -> dict:
    """Parse the extracted text from a Med Bed report into structured data."""
    patient_info = _extract_patient_info(text)

    # Extract the report generation timestamp BEFORE stripping timestamps
    report_generated_at = _extract_report_timestamp(text)

    entries = _extract_entries(text)

    logger.info(
        "Parsed Med Bed report: patient=%s %s, entries=%d, generated_at=%s",
        patient_info.get("first_name", "?"),
        patient_info.get("last_name", "?"),
        len(entries),
        report_generated_at,
    )

    return {
        "patient_info": patient_info,
        "entries": entries,
        "report_generated_at": report_generated_at,
    }


def _extract_patient_info(text: str) -> dict:
    """Extract patient demographics from the report header.

    The Med Bed PDF uses a column-based layout (via pdftotext -layout):
      Line N:   "FIRST NAME:                   LAST NAME:            MIDDLE NAME:"
      Line N+1: "                 Ballu                    Patel"
    Multiple fields share a single line; values appear on the next line at
    matching column positions.  We locate each field label's column offset,
    then read the value from the next line at that same horizontal position.
    """
    info: dict = {}

    lines = text.split("\n")[:30]

    # Canonical field labels (uppercase) → output key
    field_map = {
        "FIRST NAME": "first_name",
        "LAST NAME": "last_name",
        "MIDDLE NAME": "middle_name",
        "AGE": "age",
        "BITHDAY": "birthday",   # Typo in original report
        "BIRTHDAY": "birthday",
        "ADDRESS": "address",
        "BLOOD GROUP": "blood_group",
        "PHONE": "phone",
    }

    # Pass 1: find column positions of each field label
    # Each hit is (line_index, col_start, col_end_of_label, field_key)
    hits: list[tuple[int, int, int, str]] = []
    for i, line in enumerate(lines):
        upper = line.upper()
        for label, key in field_map.items():
            label_with_colon = label + ":"
            col = upper.find(label_with_colon)
            if col != -1:
                hits.append((i, col, col + len(label_with_colon), key))

    # Sort hits by line, then column
    hits.sort(key=lambda h: (h[0], h[1]))

    # Pass 2: extract values using column positions
    for idx, (line_idx, col_start, col_end, field_key) in enumerate(hits):
        # Determine the column range for this field's value.
        # It extends from col_start to just before the next field on the same line,
        # or to end of line if this is the last field on the line.
        same_line_hits = [h for h in hits if h[0] == line_idx and h[1] > col_start]
        if same_line_hits:
            col_right = same_line_hits[0][1]
        else:
            col_right = None  # extends to end of line

        # First, try to get value from the same line after the colon
        line = lines[line_idx]
        after_colon = line[col_end:col_right].strip() if col_right else line[col_end:].strip()

        if after_colon and not RE_PATIENT_FIELD.search(after_colon):
            info[field_key] = after_colon
        else:
            # Value is on a subsequent line at the same column range.
            # Skip blank lines (pdftotext -layout often inserts them).
            for offset in range(1, 4):
                if line_idx + offset >= len(lines):
                    break
                next_line = lines[line_idx + offset]
                if not next_line.strip():
                    continue  # skip blank line
                if RE_PATIENT_FIELD.search(next_line):
                    break  # hit another field label, stop
                # Pad the line in case it's shorter than the column position
                padded = next_line.ljust(col_end)
                value_slice = (
                    padded[col_start:col_right].strip()
                    if col_right
                    else padded[col_start:].strip()
                )
                if value_slice:
                    info[field_key] = value_slice
                break

    # Clean up age to int
    if "age" in info:
        try:
            info["age"] = int(re.search(r"\d+", info["age"]).group())
        except (AttributeError, ValueError):
            info.pop("age", None)

    return info


def _extract_entries(text: str) -> list[dict]:
    """Extract all condition entries from the report text.

    Parses the structured format:
      CONDITION_NAME [# MARKER]
                                            0.xxx
                     ANATOMICAL LOCATION (optional)
    """
    entries = []

    # Clean up the text: remove navigation tabs, page footers, timestamps
    text = RE_NAV_TABS.sub("", text)
    text = RE_PAGE_FOOTER.sub("", text)
    text = RE_TIMESTAMP.sub("", text)

    lines = text.split("\n")

    current_section = None  # e.g., "A) SIMULAR PROCESSES"
    current_organ_system = None  # e.g., "02 DIGESTIVE SYSTEM"
    current_anatomical_location = None  # Persists until changed

    i = 0
    while i < len(lines):
        line = lines[i].strip()

        # Skip empty lines
        if not line:
            i += 1
            continue

        # Check for major section header (A, B, C, D, E)
        section_match = RE_SECTION_HEADER.match(line)
        if section_match:
            current_section = f"{section_match.group(1)}) {section_match.group(2)}"
            i += 1
            continue

        # Check for "C # (INV) PATHOLOGY" or "E # (INV) MICROORGANISMS" headers
        if "# (INV)" in line:
            current_section = line.strip()
            i += 1
            continue

        # Check for organ system header (e.g., "02 DIGESTIVE SYSTEM")
        organ_match = RE_ORGAN_SYSTEM.match(line)
        if organ_match:
            num = organ_match.group(1)
            name = organ_match.group(2).strip()
            current_organ_system = f"{num} {name}"
            i += 1
            continue

        # Skip known non-entry lines
        if line.startswith("Summary Report") or line.startswith("C #"):
            i += 1
            continue

        # Check if this line is an anatomical location (indented, ALL CAPS, no score)
        # Anatomical locations are indented and appear after or between condition lines
        is_indented = lines[i].startswith("     ") or lines[i].startswith("\t")
        has_score = bool(RE_SCORE.search(line))

        if is_indented and not has_score and line.isupper() and len(line) > 3:
            # This is likely an anatomical location
            # Check it's not an organ system header
            if not RE_ORGAN_SYSTEM.match(line):
                current_anatomical_location = line.strip()
                i += 1
                continue

        # Try to parse as a condition entry
        # A condition line has a name (possibly with marker) and a score somewhere
        score_match = RE_SCORE.search(line)
        if score_match:
            score = float(score_match.group(1))
            # The condition name is everything before the score
            condition_part = line[: score_match.start()].strip()

            if condition_part:
                # Extract marker if present (e.g., "# D")
                marker = None
                marker_match = RE_MARKER.search(condition_part)
                if marker_match:
                    marker = marker_match.group(1)
                    condition_part = condition_part[: marker_match.start()].strip()

                # Look ahead for anatomical location on next non-empty line
                anatomy = current_anatomical_location
                j = i + 1
                while j < len(lines) and not lines[j].strip():
                    j += 1
                if j < len(lines):
                    next_line = lines[j]
                    next_stripped = next_line.strip()
                    is_next_indented = next_line.startswith("     ") or next_line.startswith("\t")
                    if (
                        is_next_indented
                        and not RE_SCORE.search(next_stripped)
                        and next_stripped.isupper()
                        and len(next_stripped) > 3
                        and not RE_ORGAN_SYSTEM.match(next_stripped)
                    ):
                        anatomy = next_stripped
                        current_anatomical_location = anatomy

                entries.append(
                    {
                        "condition_name": condition_part,
                        "score": score,
                        "anatomical_location": anatomy,
                        "organ_system": current_organ_system,
                        "report_section": current_section,
                        "marker": marker,
                    }
                )
            else:
                # Score on its own line — this means the condition was on the previous
                # non-empty line. Look back.
                for k in range(i - 1, max(i - 5, -1), -1):
                    prev = lines[k].strip()
                    if prev and not RE_SCORE.search(prev) and not is_skip_line(prev):
                        # Check if this looks like a condition name
                        marker = None
                        marker_match = RE_MARKER.search(prev)
                        if marker_match:
                            marker = marker_match.group(1)
                            prev = prev[: marker_match.start()].strip()

                        # Look ahead for anatomy
                        anatomy = current_anatomical_location
                        j = i + 1
                        while j < len(lines) and not lines[j].strip():
                            j += 1
                        if j < len(lines):
                            next_line = lines[j]
                            next_stripped = next_line.strip()
                            is_next_indented = next_line.startswith("     ") or next_line.startswith("\t")
                            if (
                                is_next_indented
                                and not RE_SCORE.search(next_stripped)
                                and next_stripped.isupper()
                                and len(next_stripped) > 3
                                and not RE_ORGAN_SYSTEM.match(next_stripped)
                            ):
                                anatomy = next_stripped
                                current_anatomical_location = anatomy

                        entries.append(
                            {
                                "condition_name": prev,
                                "score": score,
                                "anatomical_location": anatomy,
                                "organ_system": current_organ_system,
                                "report_section": current_section,
                                "marker": marker,
                            }
                        )
                        break

        i += 1

    # Deduplicate entries (same condition + organ system)
    seen = set()
    unique_entries = []
    for entry in entries:
        key = (entry["condition_name"], entry.get("organ_system"), entry.get("report_section"))
        if key not in seen:
            seen.add(key)
            unique_entries.append(entry)

    return unique_entries


def is_skip_line(line: str) -> bool:
    """Check if a line should be skipped during condition parsing."""
    skip_patterns = [
        "Summary Report",
        "FIRST NAME",
        "LAST NAME",
        "MIDDLE NAME",
        "AGE:",
        "BITHDAY",
        "BIRTHDAY",
        "ADDRESS",
        "BLOOD GROUP",
        "PHONE",
        "GI ",
        "Cardiovascular",
        "PM",
        "AM",
    ]
    return any(p in line for p in skip_patterns)


def _parse_csv(file_bytes: bytes) -> dict:
    """Parse a CSV report file."""
    df = pd.read_csv(io.BytesIO(file_bytes))

    # Normalize column names
    col_map = {}
    for col in df.columns:
        lower = col.lower().strip()
        if "condition" in lower or "pathology" in lower:
            col_map[col] = "condition_name"
        elif "score" in lower or "value" in lower or "deviation" in lower:
            col_map[col] = "score"
        elif "anatomy" in lower or "location" in lower:
            col_map[col] = "anatomical_location"
        elif "organ" in lower or "system" in lower:
            col_map[col] = "organ_system"
        elif "section" in lower:
            col_map[col] = "report_section"
        elif "green" in lower:
            col_map[col] = "green_ratio"
        elif "red" in lower:
            col_map[col] = "red_ratio"

    df = df.rename(columns=col_map)

    entries = []
    for _, row in df.iterrows():
        entry = {
            "condition_name": str(row.get("condition_name", "Unknown")),
            "score": float(row.get("score", 0.0)),
            "anatomical_location": str(row.get("anatomical_location", ""))
            if pd.notna(row.get("anatomical_location"))
            else None,
            "organ_system": str(row.get("organ_system", ""))
            if pd.notna(row.get("organ_system"))
            else None,
            "report_section": str(row.get("report_section", ""))
            if pd.notna(row.get("report_section"))
            else None,
            "marker": None,
        }
        entries.append(entry)

    return {"patient_info": {}, "entries": entries}


def _parse_json(file_bytes: bytes) -> dict:
    """Parse a JSON report file."""
    data = json.loads(file_bytes.decode("utf-8"))

    if isinstance(data, list):
        # Assume list of entries
        entries = []
        for item in data:
            entries.append(
                {
                    "condition_name": item.get("condition_name", item.get("condition", "Unknown")),
                    "score": float(item.get("score", item.get("value", 0.0))),
                    "anatomical_location": item.get("anatomical_location", item.get("anatomy")),
                    "organ_system": item.get("organ_system"),
                    "report_section": item.get("report_section"),
                    "marker": item.get("marker"),
                }
            )
        return {"patient_info": {}, "entries": entries}
    elif isinstance(data, dict):
        return {
            "patient_info": data.get("patient_info", {}),
            "entries": data.get("entries", []),
        }
    else:
        raise ValueError("JSON must be a list of entries or a dict with 'entries' key")


def _parse_image(file_bytes: bytes) -> dict:
    """Parse an image file using OCR."""
    try:
        import pytesseract
        from PIL import Image

        image = Image.open(io.BytesIO(file_bytes))
        text = pytesseract.image_to_string(image)
        return _parse_medbed_text(text)
    except Exception as e:
        raise ValueError(f"Image OCR failed: {e}")
